version: '3.3'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        volumes:
          - ./data/db:/data/db
        ports:
          - 27017:27017

    frontend:
        build: ./Frontend
        command: npm start
        ports:
            - 4200:4200
        expose:
            - 4200
        volumes:
            - ./data/front:/data/front

    backend:
        build: ./Backend
        container_name: "backend"
        volumes:
          - ./tmp/db:/var/lib/mongodb/data
        ports:
          - 8000:8000
        links:
          - mongodb
        depends_on:
          - mongodb
